const API_URL = 'http://localhost:3000'
// const API_URL = ''
const IMAGE_STATIC = '/uploads/'
const LOGO_URL = '/img/logo.png'
const BACK_IMG_URL = '/img/back.png'
const DELETE_IMG_URL = '/img/delete.svg'
const FILL_MESSAGE = 'Необходимо заполнить корректно все поля.'
const CONNECT_MESSAGE = 'Проверьте интернет соединение и попробуйте еще раз.'
const IMAGE_UPLOAD_ERROR = 'Не удалось загрузить изображение. Допустимый формат: .jpg/.png. Размер не должен привышать 2мб.'
const SUCCESS_MESSAGE = 'Успешно'
export { IMAGE_STATIC, API_URL, LOGO_URL, BACK_IMG_URL, DELETE_IMG_URL, FILL_MESSAGE, CONNECT_MESSAGE, SUCCESS_MESSAGE, IMAGE_UPLOAD_ERROR }
